### ISSUE TITLE
Hitting Github API rate limit: "Unable to get release from repo" "API Requests Remaining : [0]"

### ISSUE THREAD

**Issue by max-rocket-internet** [tokiwong/helm-switcher#11]
**Describe the bug**

The problem is we are on a large company VPN and our IP address(es) have hit the Github rate limit. This stops helmswitch from working:

```
$ helmswitch 2.16.10
API Requests Remaining : [0]
Your Rate Limit will reset at : Your Rate Limit will reset at : Your Rate Limit will reset at : API Requests Remaining : [0]
Your Rate Limit will reset at : 2020-09-09 15:20:20 +0200 CEST
2020/09/09 15:08:56 Unable to get release from repo
2020-09-09 15:20:20 +0200 CEST
API Requests Remaining : [0]
2020/09/09 15:08:56 Unable to get release from repo
```

Would it be possible to get releases without using the API? Does anyone else hit this issue?

**Comment by tokiwong** [comment]
Unfortunately, Helm uses the GitHub API to explore their releases, which helmswitch uses to generate a list to find any given version.  

However, the actual download links for the binaries and checksums are hosted on `get.helm.sh`, and while it's not a searchable URL, I can see a workaround where helmswitch can bypass the GitHub API and directly hit `get.helm.sh/` if you know the exact helm version you want.

ex: `helmswitch 3.3.1` downloads helm v3.3.1, and currently validates if the version exists by hitting the github API from the releases page, but I could explore other ways to validate that avoids github altogether

**Comment by max-rocket-internet** [comment]
Or what about if I select a version that I already have downloaded and installed then just skip checking releases all together?

**Comment by tokiwong** [comment]
that works too

**Comment by max-rocket-internet** [comment]
I think this way would make more sense anyway as technically the call to the Github API is not needed in this case. Also then we could switch helm versions without internet connection 🙂

**Comment by max-rocket-internet** [comment]
That was quick! Thank you @tokiwong 💖

**Comment by tokiwong** [comment]
No problem! The updated binary can be downloaded from the assets folder under the [0.0.5 release](https://github.com/tokiwong/helm-switcher/releases/tag/v0.0.5) 

Or run `brew update && brew reinstall tokiwong/tap/helm-switcher` if you're on mac
