### ISSUE TITLE
[Feature Request] Brew install

### ISSUE THREAD

**Issue by Adelbertt** [tokiwong/helm-switcher#4]
Hi, 

I really like you project as we are also in the midst of migrating our helm from v2 to 3v.

It would be really cool if you could put it on brew! It would be easy to install and maintain update as a end user.

Cheers!

**Comment by tokiwong** [comment]
@Adelbertt homebrew installation has been included!

Please give it a shot with `brew install tokiwong/tap/helm-switcher`

**Comment by Adelbertt** [comment]
Hi,

To install it works but i'm getting, 
`(⎈ |N/A:N/A)➜  ~ helmswitch
2020/04/27 07:51:36 Unable to get release from repo`

**Comment by tokiwong** [comment]
@Adelbertt thanks for confirming the brew install, i'll go ahead and close this issue. 

As for `unable to get release from repo`, the current go code submits unauthenticated github api requests to gather releases, and there's currently a rate limit of 60 requests per hour, or 5000 requests per hour if you're authenticated through a git token.  The quickest workaround would be to hop on to another network or VPN and continue, but I understand that's clunky.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.
--https://developer.github.com/v3/#rate-limiting

If you have a use case for switching between helm versions multiple times within an hour (outside of initial functionality testing), please submit another issue regarding the `Unable to get release from repo`
