### ISSUE TITLE
Verify package checksum on install

### ISSUE THREAD

**Issue by jdolitsky** [tokiwong/helm-switcher#5]
Neat project! Been looking for something like this.

It would be great if the sha256 checksum of the package were verified on download. You can see how that is done in the bash install script: https://github.com/helm/helm/blob/8e1c34ef045b350c68974f8ca12e2cb6d245d3f3/scripts/get-helm-3#L132

If you append ".shasum" to the download path, there is a text file with the checksum of the .tar.gz file

**Comment by tokiwong** [comment]
@jdolitsky thanks for the request! This has been resolved in Release [v0.0.4](https://github.com/tokiwong/helm-switcher/releases/tag/v0.0.4)
